import {useMutation,useQuery} from '@tanstack/react-query';
import {Link,NavLink,Route,Routes} from 'react-router-dom';
import {Activity,BarChart3,FileText,FolderOpen,Instagram,Layers,Menu,MonitorCog,Moon,Sun,Users} from 'lucide-react';
import {api,instagramApi,type Dashboard} from './api';
import {useUI} from './store';
import {Accounts,InstagramPosts,Posts,Topics} from './pages';
import {Documents} from './documents';

const nav=[['/','Dashboard',BarChart3],['/instagram','Instagram',Instagram],['/documents','Belgeler',FolderOpen],['/accounts','Hesaplar',Users],['/posts','Gönderiler',FileText],['/topics','Konular',Layers],['/settings','Ayarlar',MonitorCog]] as const;
function DashboardPage(){const {data,isLoading,error}=useQuery({queryKey:['dashboard'],queryFn:()=>api.get<Dashboard>('/dashboard').then(r=>r.data)});if(isLoading)return <Loading/>;if(error)return <Error text="Dashboard verileri alınamadı. Redis bağlantısını kontrol edin."/>;const cards=[['Takip edilen hesap',data!.trackedAccounts],['Analiz edilen gönderi',data!.analyzedPosts],['Bugün analiz edilen',data!.todayAnalyzed],['AI eşleşmeleri',data!.aiMatches]];return <section><Heading title="Dashboard" text="Takip ve analiz sisteminizin genel görünümü."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([name,value])=><article className="card" key={name}><p>{name}</p><strong>{value}</strong></article>)}</div><article className="card mt-6"><h2>Sistem durumu</h2><p className="status"><i/> {data!.status==='healthy'?'Tüm servisler çalışıyor':data!.status}</p><p className="muted">Son tarama: {data!.lastScanAt?new Date(data!.lastScanAt).toLocaleString('tr-TR'):'Henüz tarama yapılmadı'}</p></article></section>}
function Settings(){return <section><Heading title="Ayarlar" text="Servis ve zamanlama ayarları ortam değişkenlerinden yönetilir."/><div className="card"><h2>Güvenli yapılandırma</h2><p className="muted">API anahtarlarını arayüze kaydetmeyin. OpenAI entegrasyonu temel arama için zorunlu değildir.</p></div></section>}
function InstagramPage(){
  const browser=useQuery({queryKey:['browser-status'],queryFn:()=>instagramApi.get('/instagram/browser/status').then(r=>r.data),refetchInterval:5000});
  const open=useMutation({mutationFn:()=>instagramApi.post('/instagram/browser/open'),onSuccess:()=>browser.refetch()});
  return <>{browser.data&&!browser.data.instagram_authenticated&&<div className="card"><b>Instagram oturumu gerekiyor</b><p>Açılan Chromium penceresinden Instagram'a giriş yapın. Şifreniz uygulama tarafından okunmaz veya kaydedilmez.</p><button className="primary" onClick={()=>open.mutate()} disabled={open.isPending}>Instagram Tarayıcısını Aç</button><button onClick={()=>browser.refetch()}>Oturumu Kontrol Et</button>{open.error&&<Error text="Instagram tarayıcısı açılamadı."/>}</div>}<FullHistoryControls/><InstagramPosts/></>
}
function FullHistoryControls(){
  const accounts=useQuery({queryKey:['full-sync-accounts'],queryFn:()=>instagramApi.get('/instagram/accounts').then(r=>r.data as {id:string;username:string}[]),refetchInterval:5000});
  return <>{accounts.data?.map(account=><FullHistoryAccount key={account.id} account={account}/>)}</>
}
function FullHistoryAccount({account}:{account:{id:string;username:string}}){
  const status=useQuery({queryKey:['full-sync-status',account.id],queryFn:()=>instagramApi.get(`/instagram/accounts/${account.id}/sync-status`).then(r=>r.data).catch(e=>e.response?.status===404?null:Promise.reject(e)),refetchInterval:3000});
  const full=useMutation({mutationFn:()=>instagramApi.post(`/instagram/accounts/${account.id}/full-sync`,{full_history:true,max_posts:2500}),onSuccess:()=>status.refetch()});
  const cancel=useMutation({mutationFn:()=>instagramApi.post(`/instagram/accounts/${account.id}/sync-cancel`),onSuccess:()=>status.refetch()});
  const running=['queued','running','paused_rate_limit'].includes(status.data?.status);
  return <div className="card"><b>@{account.username} geçmiş taraması</b><div className="inline-form"><button onClick={()=>instagramApi.post(`/instagram/accounts/${account.id}/sync`)}>Yeni Gönderileri Kontrol Et</button><button className="primary" disabled={running||full.isPending} onClick={()=>full.mutate()}>Tüm Geçmişi Tara</button>{running&&<button className="danger" onClick={()=>cancel.mutate()}>İptal Et</button>}</div>{status.data&&<p className="muted">Bulunan: {Number(status.data.discovered_count||0).toLocaleString('tr-TR')} · İşlenen: {Number(status.data.processed_count||0).toLocaleString('tr-TR')} · Kaydedilen: {Number(status.data.saved_count||0).toLocaleString('tr-TR')} · Güncellenen: {Number(status.data.updated_count||0).toLocaleString('tr-TR')} · Atlanan: {Number(status.data.skipped_count||0).toLocaleString('tr-TR')} · Tarama turu: {status.data.scroll_round||0} · Durum: {status.data.status}</p>}{full.error&&<Error text={(full.error as any)?.response?.data?.message||'Geçmiş taraması başlatılamadı.'}/>}</div>
}
export default function App(){const dark=useUI(s=>s.dark),toggle=useUI(s=>s.toggle);return <div className={dark?'dark app':'app'}><aside><Link className="brand" to="/"><Activity/> Insight<span>AI</span></Link><nav>{nav.map(([to,label,Icon])=><NavLink end={to==='/'} to={to} key={to}><Icon size={18}/>{label}</NavLink>)}</nav></aside><main><header><Menu className="mobile"/><div className="grow"/><button className="icon" onClick={toggle} aria-label="Tema değiştir">{dark?<Sun/>:<Moon/>}</button></header><Routes><Route path="/" element={<DashboardPage/>}/><Route path="/instagram" element={<InstagramPage/>}/><Route path="/documents" element={<Documents/>}/><Route path="/accounts" element={<Accounts/>}/><Route path="/posts" element={<Posts/>}/><Route path="/topics" element={<Topics/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Error text="Bu sayfa bulunamadı."/>}/></Routes></main></div>}
export function Heading({title,text}:{title:string;text:string}){return <div className="heading"><div><h1>{title}</h1><p>{text}</p></div></div>}
export function Loading(){return <div className="card">Yükleniyor…</div>}
export function Error({text='Veri yüklenirken bir hata oluştu.'}:{text?:string}){return <div className="card error">{text}</div>}
