import {useQuery} from '@tanstack/react-query';
import {Link,NavLink,Route,Routes} from 'react-router-dom';
import {Activity,BarChart3,FileText,Instagram,Layers,Menu,MonitorCog,Moon,Sun,Users} from 'lucide-react';
import {api,type Dashboard} from './api';
import {useUI} from './store';
import {Accounts,InstagramPosts,Posts,Topics} from './pages';

const nav=[['/','Dashboard',BarChart3],['/instagram','Instagram',Instagram],['/accounts','Hesaplar',Users],['/posts','Gönderiler',FileText],['/topics','Konular',Layers],['/settings','Ayarlar',MonitorCog]] as const;
function DashboardPage(){const {data,isLoading,error}=useQuery({queryKey:['dashboard'],queryFn:()=>api.get<Dashboard>('/dashboard').then(r=>r.data)});if(isLoading)return <Loading/>;if(error)return <Error text="Dashboard verileri alınamadı. Redis bağlantısını kontrol edin."/>;const cards=[['Takip edilen hesap',data!.trackedAccounts],['Analiz edilen gönderi',data!.analyzedPosts],['Bugün analiz edilen',data!.todayAnalyzed],['AI eşleşmeleri',data!.aiMatches]];return <section><Heading title="Dashboard" text="Takip ve analiz sisteminizin genel görünümü."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([name,value])=><article className="card" key={name}><p>{name}</p><strong>{value}</strong></article>)}</div><article className="card mt-6"><h2>Sistem durumu</h2><p className="status"><i/> {data!.status==='healthy'?'Tüm servisler çalışıyor':data!.status}</p><p className="muted">Son tarama: {data!.lastScanAt?new Date(data!.lastScanAt).toLocaleString('tr-TR'):'Henüz tarama yapılmadı'}</p></article></section>}
function Settings(){return <section><Heading title="Ayarlar" text="Servis ve zamanlama ayarları ortam değişkenlerinden yönetilir."/><div className="card"><h2>Güvenli yapılandırma</h2><p className="muted">API anahtarlarını arayüze kaydetmeyin. OpenAI entegrasyonu temel arama için zorunlu değildir.</p></div></section>}
export default function App(){const dark=useUI(s=>s.dark),toggle=useUI(s=>s.toggle);return <div className={dark?'dark app':'app'}><aside><Link className="brand" to="/"><Activity/> Insight<span>AI</span></Link><nav>{nav.map(([to,label,Icon])=><NavLink end={to==='/'} to={to} key={to}><Icon size={18}/>{label}</NavLink>)}</nav></aside><main><header><Menu className="mobile"/><div className="grow"/><button className="icon" onClick={toggle} aria-label="Tema değiştir">{dark?<Sun/>:<Moon/>}</button></header><Routes><Route path="/" element={<DashboardPage/>}/><Route path="/instagram" element={<InstagramPosts/>}/><Route path="/accounts" element={<Accounts/>}/><Route path="/posts" element={<Posts/>}/><Route path="/topics" element={<Topics/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Error text="Bu sayfa bulunamadı."/>}/></Routes></main></div>}
export function Heading({title,text}:{title:string;text:string}){return <div className="heading"><div><h1>{title}</h1><p>{text}</p></div></div>}
export function Loading(){return <div className="card">Yükleniyor…</div>}
export function Error({text='Veri yüklenirken bir hata oluştu.'}:{text?:string}){return <div className="card error">{text}</div>}
